### 텐서 만들기

In [ ]:
import torch

In [ ]:
data_list = [1, 2]

tensor = torch.tensor(data_list)
tensor

tensor([1, 2])

In [ ]:
type(tensor)

torch.Tensor

In [ ]:
print(f'data type: {tensor.dtype}')
print(f'number of dimensions: {tensor.ndim}')
print(f'shape: {tensor.shape}')

data type: torch.int64
number of dimensions: 1
shape: torch.Size([2])


In [ ]:
print(f'size: {tensor.size()}')

size: torch.Size([2])


In [ ]:
import numpy as np

data_np = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

tensor_np = torch.tensor(data_np)
tensor_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
tensor_from_numpy = torch.from_numpy(data_np)
tensor_from_numpy

tensor([[1, 2],
        [3, 4]])

In [ ]:
data_np[0, 0] = -1

print(f'torch.tensor() result\n{tensor_np}')
print(f'torch.from_numpy() result\n{tensor_from_numpy}')

torch.tensor() result
tensor([[1, 2],
        [3, 4]])
torch.from_numpy() result
tensor([[-1,  2],
        [ 3,  4]])


In [ ]:
print(tensor.dtype)
print(tensor_np.dtype)

torch.int64
torch.int64


In [ ]:
tensor = torch.tensor([1, 1.5])
tensor.dtype

torch.float32

In [ ]:
tensor = torch.tensor([1, 2, 3], dtype = torch.float32)
tensor.dtype

torch.float32

### 텐서의 변환과 연산

In [ ]:
import numpy as np
import torch

In [ ]:
tensor = torch.ones(2,2)

In [ ]:
np_array = tensor.numpy()
np_array

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
np_array2 = np.array(tensor)
np_array2

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
tensor[0, 0] = -1

In [ ]:
print(f'torch.tensor() result\n{np_array}')
print(f'torch.from_numpy() result\n{np_array2}')

torch.tensor() result
[[-1.  1.]
 [ 1.  1.]]
torch.from_numpy() result
[[1. 1.]
 [1. 1.]]


In [ ]:
a = torch.tensor([[1, 2],[3, 4]])
b = torch.tensor([[5, 6],[7, 8]])

In [ ]:
a + b

tensor([[ 6,  8],
        [10, 12]])

In [ ]:
torch.add(a,b)

tensor([[ 6,  8],
        [10, 12]])

In [ ]:
a*b

tensor([[ 5, 12],
        [21, 32]])

In [ ]:
torch.multiply(a,b)

tensor([[ 5, 12],
        [21, 32]])

In [ ]:
a = torch.tensor(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8]
    ]
)

b = torch.tensor(
    [
        [1,0,0],
        [0,0,1],
        [1,1,0],

    ]
)

print(f'a의 열 개수: {a.shape[1]}')
print(f'b의 행 개수: {b.shape[0]}')

a의 열 개수: 2
b의 행 개수: 3


In [ ]:
torch.matmul(a,b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x2 and 3x3)

In [ ]:
a = torch.tensor(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8]
    ]
)

b = torch.tensor(
    [
        [1,0,0],
        [0,0,1],

    ]
)

print(f'a의 열 개수: {a.shape[1]}')
print(f'b의 행 개수: {b.shape[0]}')

a의 열 개수: 2
b의 행 개수: 2


In [ ]:
torch.matmul(a,b)

tensor([[1, 0, 2],
        [3, 0, 4],
        [5, 0, 6],
        [7, 0, 8]])

In [ ]:
a@b

tensor([[1, 0, 2],
        [3, 0, 4],
        [5, 0, 6],
        [7, 0, 8]])

In [ ]:
tensor = torch.tensor([3,5,7,9,10])

In [ ]:
tensor[0]

tensor(3)

In [ ]:
tensor[2]

tensor(7)

In [ ]:
tensor[-1]

tensor(10)

In [ ]:
tensor[:2]

tensor([3, 5])

In [ ]:
tensor_2d = torch.tensor(
    [
        [1,3,5,7,9],
        [2,4,6,8,10],
    ]
)

In [ ]:
tensor_2d[0, 0]

tensor(1)

In [ ]:
tensor_2d[0][0]

tensor(1)

In [ ]:
tensor_2d[0, 3:]

tensor([7, 9])

### 브로드캐스팅

In [ ]:
import torch

In [ ]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1, 2],
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([3])


In [ ]:
a + b

tensor([[2, 1, 5],
        [5, 4, 8]])

In [ ]:
a + 1

tensor([[2, 3, 4],
        [5, 6, 7]])

In [ ]:
a * 2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

### 텐서의 형태 바꾸기

In [ ]:
x = torch.randn(3,4)
x

tensor([[ 0.6047, -0.7926, -1.9815, -0.3106],
        [ 0.9164, -0.3378, -1.0906, -0.1863],
        [-0.5201, -0.4501, -0.9556,  0.0956]])

In [ ]:
res0 = x.reshape(2, 6)
res0

tensor([[ 0.6047, -0.7926, -1.9815, -0.3106,  0.9164, -0.3378],
        [-1.0906, -0.1863, -0.5201, -0.4501, -0.9556,  0.0956]])

In [ ]:
res1 = x.reshape(-1, 2, 3)
res1.size()

torch.Size([2, 2, 3])

In [ ]:
x = torch.randn(2, 3, 4)
permuted = x.permute(2, 0, 1)

In [ ]:
permuted.size()

torch.Size([4, 2, 3])

In [ ]:
x = torch.randn(1, 28, 1, 28)

In [ ]:
result0 = x.squeeze()
result0.size()

torch.Size([28, 28])

In [ ]:
result1 = x.squeeze(2)
result1.size()

torch.Size([1, 28, 28])

### 텐서 합치기

In [ ]:
x = torch.zeros(2,3)
y = torch.ones(2,3)

In [ ]:
cat0 = torch.cat([x, y], dim = 0)
cat1 = torch.cat([x, y], dim = 1)

In [ ]:
print(cat0)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
print(cat1)

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])


In [ ]:
stack_result = torch.stack([x, y], dim = 0)
cat_result = torch.cat([x, y], dim = 0)

In [ ]:
stack_result

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
cat_result

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])