In [1]:
import tensorflow as tf
import keras

In [3]:
model_sequential = keras.Sequential(
    [
        keras.Input(shape = (8, )),
        keras.layers.Dense(4, activation = "relu"),
        keras.layers.Dense(6, activation = "relu"),
        keras.layers.Dense(2, activation = "softmax"),
    ],
)

In [5]:
def add_one(x):
    return x + 1

print(add_one(10))

11


In [11]:
inputs = keras.Input(shape = (8, ))
h0 = keras.layers.Dense(4, activation = "relu")(inputs)

In [13]:
random_tensor = tf.random.normal([2, 8])
y = keras.layers.Dense(4, activation = "relu")(random_tensor)

In [15]:
print(f"h0:\n{h0}\n")
print(f"y:\n{y}")

h0:
<KerasTensor shape=(None, 4), dtype=float32, sparse=False, name=keras_tensor_8>

y:
[[1.6975296  0.         2.5204387  0.        ]
 [0.1648444  0.43086553 2.157658   0.        ]]


In [17]:
inputs = keras.Input(shape = (8, ))
h0 = keras.layers.Dense(4, activation = "relu")(inputs)
h1 = keras.layers.Dense(6, activation = "relu")(h0)
outputs = keras.layers.Dense(2, activation = "softmax")(h1)
model = keras.Model(inputs = inputs, outputs = outputs, name = "My Functional Model")

In [19]:
model.summary()

Model: "My Functional Model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)           │ (None, 8)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 4)                   │              36 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 6)                   │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 2)                   │              14 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 80 (320.00 B)

 Trainable params: 80 (320.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
random_input = tf.random.normal([3, 8])
y = model(random_input)

In [23]:
print(f"출력 텐서 shape: {y.shape}")

출력 텐서 shape: (3, 2)


In [25]:
# Functional API로 복잡한 모델 만들기

In [29]:
inputs0 = keras.Input(shape = (4, ))
h0_0 = keras.layers.Dense(8, activation = "relu")(inputs0)

inputs1 = keras.Input(shape = (6, ))
h0_1 = keras.layers.Dense(4, activation = "relu")(inputs1)

inputs2 = keras.Input(shape = (2, ))

h1 = keras.layers.Concatenate()([h0_0, h0_1, inputs2])

outputs0 = keras.layers.Dense(8)(h1)
outputs1 = keras.layers.Dense(2)(h1)

model = keras.Model(
    inputs = [inputs0, inputs1, inputs2],
    outputs = [outputs0, outputs1],
)

In [43]:
x0 = tf.random.normal([3, 4])
x1 = tf.random.normal([3, 6])
x2 = tf.random.normal([3, 2])

y = model([x0, x1, x2])

In [45]:
y

[<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[-0.3954648 , -0.00264072, -0.7168668 ,  0.54537964,  0.20280641,
          0.42920673, -0.44134167, -0.07733229],
        [-0.5817325 ,  0.21766317, -0.44830745,  0.48394904, -0.79013693,
          0.5452383 ,  0.05320725,  0.5450447 ],
        [-1.4381207 ,  0.5246835 , -0.429006  ,  0.55778587, -0.34462965,
          0.75060964,  0.61465305, -0.00283945]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.553304  ,  0.8736481 ],
        [-0.23739845,  0.76540864],
        [-0.87494963,  0.5950003 ]], dtype=float32)>]