In [1]:
import tensorflow as tf
import keras

In [9]:
layer0 = keras.layers.Dense(4, activation = "relu")
layer1 = keras.layers.Dense(6, activation = "relu")
layer2 = keras.layers.Dense(2, activation = "softmax")

model = keras.Sequential(
    [layer0, layer1, layer2],
    name = "Model 1"
)

In [13]:
model2 = keras.Sequential(
    [
        keras.layers.Dense(4, activation = "relu"),
        keras.layers.Dense(6, activation = "relu"),
        keras.layers.Dense(2, activation = "softmax"),
    ],
    name = "Model 2"
)

In [15]:
model3 = keras.Sequential([])

model3.add(keras.layers.Dense(4, activation = "relu"))
model3.add(keras.layers.Dense(6, activation = "relu"))
model3.add(keras.layers.Dense(2, activation = "softmax"))

In [17]:
x = tf.random.normal([3, 8])
y = model(x)

In [19]:
print(f"출력 텐서 shape: {y.shape}")

출력 텐서 shape: (3, 2)


In [21]:
model_with_input = keras.Sequential(
    [
        keras.Input(shape = (8, )),
        keras.layers.Dense(4, activation = "relu"),
        keras.layers.Dense(6, activation = "relu"),
        keras.layers.Dense(2, activation = "softmax"),
    ]
)

In [23]:
model_with_input = keras.Sequential(
    [
        keras.layers.Dense(4, activation = "relu", input_shape = (8, )),
        keras.layers.Dense(6, activation = "relu"),
        keras.layers.Dense(2, activation = "softmax"),
    ]
)

C:\Users\leoyo\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [25]:
model = keras.Sequential(
    [
        keras.layers.Dense(4, activation = "relu"),
        keras.layers.Dense(6, activation = "relu"),
        keras.layers.Dense(2, activation = "softmax"),
    ],
    name = "My Sequential Model"
)

In [27]:
model.summary()

Model: "My Sequential Model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.weights

[]

In [35]:
x = tf.random.normal([3, 8])
y = model(x)

In [37]:
model.summary()

Model: "My Sequential Model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                     │ (3, 4)                      │              36 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (3, 6)                      │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (3, 2)                      │              14 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 80 (320.00 B)

 Trainable params: 80 (320.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.weights

[<KerasVariable shape=(8, 4), dtype=float32, path=My Sequential Model/dense_16/kernel>,
 <KerasVariable shape=(4,), dtype=float32, path=My Sequential Model/dense_16/bias>,
 <KerasVariable shape=(4, 6), dtype=float32, path=My Sequential Model/dense_17/kernel>,
 <KerasVariable shape=(6,), dtype=float32, path=My Sequential Model/dense_17/bias>,
 <KerasVariable shape=(6, 2), dtype=float32, path=My Sequential Model/dense_18/kernel>,
 <KerasVariable shape=(2,), dtype=float32, path=My Sequential Model/dense_18/bias>]

In [41]:
model = keras.Sequential(
    [
        keras.Input(shape = (8, )),
        keras.layers.Dense(4, activation = "relu"),
        keras.layers.Dense(6, activation = "relu"),
        keras.layers.Dense(2, activation = "softmax"),
    ]
)

In [43]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_19 (Dense)                     │ (None, 4)                   │              36 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_20 (Dense)                     │ (None, 6)                   │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_21 (Dense)                     │ (None, 2)                   │              14 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 80 (320.00 B)

 Trainable params: 80 (320.00 B)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.weights

[<KerasVariable shape=(8, 4), dtype=float32, path=sequential_3/dense_19/kernel>,
 <KerasVariable shape=(4,), dtype=float32, path=sequential_3/dense_19/bias>,
 <KerasVariable shape=(4, 6), dtype=float32, path=sequential_3/dense_20/kernel>,
 <KerasVariable shape=(6,), dtype=float32, path=sequential_3/dense_20/bias>,
 <KerasVariable shape=(6, 2), dtype=float32, path=sequential_3/dense_21/kernel>,
 <KerasVariable shape=(2,), dtype=float32, path=sequential_3/dense_21/bias>]

In [47]:
model.get_weights()

[array([[ 0.35530227, -0.36875492,  0.05842817, -0.4735856 ],
        [-0.66689646, -0.24931815,  0.27184767, -0.5334749 ],
        [ 0.33875006, -0.20470488,  0.08220947,  0.702398  ],
        [-0.09633875, -0.16378957,  0.45322078,  0.7022887 ],
        [-0.61104333,  0.13609606, -0.01947558, -0.6622261 ],
        [-0.40604576,  0.06503779,  0.4193589 ,  0.49611026],
        [-0.0827722 ,  0.24173445, -0.27428883,  0.27896827],
        [-0.7002188 , -0.42368776,  0.64093155,  0.4228409 ]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.59359634, -0.19824713,  0.3119681 ,  0.34889722,  0.37765002,
         -0.00951701],
        [ 0.22095257, -0.22806764, -0.04367274,  0.5091218 , -0.32160625,
          0.72704554],
        [ 0.3354267 ,  0.71118164,  0.0052408 ,  0.28974283, -0.04322302,
         -0.39272457],
        [-0.45774865, -0.1393078 , -0.02726424,  0.05617654, -0.25012934,
         -0.2364816 ]], dtype=float32),
 array([0., 0., 0., 0., 0., 0.], d

In [49]:
model.layers

[<Dense name=dense_19, built=True>,
 <Dense name=dense_20, built=True>,
 <Dense name=dense_21, built=True>]

In [51]:
model.layers[0].get_weights()

[array([[ 0.35530227, -0.36875492,  0.05842817, -0.4735856 ],
        [-0.66689646, -0.24931815,  0.27184767, -0.5334749 ],
        [ 0.33875006, -0.20470488,  0.08220947,  0.702398  ],
        [-0.09633875, -0.16378957,  0.45322078,  0.7022887 ],
        [-0.61104333,  0.13609606, -0.01947558, -0.6622261 ],
        [-0.40604576,  0.06503779,  0.4193589 ,  0.49611026],
        [-0.0827722 ,  0.24173445, -0.27428883,  0.27896827],
        [-0.7002188 , -0.42368776,  0.64093155,  0.4228409 ]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [53]:
model.inputs

[<KerasTensor shape=(None, 8), dtype=float32, sparse=False, name=keras_tensor_16>]

In [97]:
keras.utils.plot_model(model, "modle_vis.png", show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.
