In [1]:
import tensorflow as tf
import keras

In [3]:
def print_dataset(dataset):
    for data in dataset:
        print(data)

In [5]:
x = [[0,0], [1,-1], [2,-2], [3,-3], [4,-4], [5,-5]]
dataset = tf.data.Dataset.from_tensor_slices(x)

In [7]:
print_dataset(dataset)

tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor([ 1 -1], shape=(2,), dtype=int32)
tf.Tensor([ 2 -2], shape=(2,), dtype=int32)
tf.Tensor([ 3 -3], shape=(2,), dtype=int32)
tf.Tensor([ 4 -4], shape=(2,), dtype=int32)
tf.Tensor([ 5 -5], shape=(2,), dtype=int32)


In [9]:
dataset_batch = dataset.batch(2)

In [11]:
print_dataset(dataset_batch)

tf.Tensor(
[[ 0  0]
 [ 1 -1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2 -2]
 [ 3 -3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 4 -4]
 [ 5 -5]], shape=(2, 2), dtype=int32)


In [13]:
dataset_batch = dataset.batch(4)

In [15]:
print_dataset(dataset_batch)

tf.Tensor(
[[ 0  0]
 [ 1 -1]
 [ 2 -2]
 [ 3 -3]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[ 4 -4]
 [ 5 -5]], shape=(2, 2), dtype=int32)


In [17]:
dataset_batch = dataset.batch(4, drop_remainder = True)

In [19]:
print_dataset(dataset_batch)

tf.Tensor(
[[ 0  0]
 [ 1 -1]
 [ 2 -2]
 [ 3 -3]], shape=(4, 2), dtype=int32)


In [21]:
dataset_shuffle = dataset.shuffle(buffer_size = 4)

In [23]:
print_dataset(dataset_shuffle)

tf.Tensor([ 1 -1], shape=(2,), dtype=int32)
tf.Tensor([ 4 -4], shape=(2,), dtype=int32)
tf.Tensor([ 3 -3], shape=(2,), dtype=int32)
tf.Tensor([ 2 -2], shape=(2,), dtype=int32)
tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor([ 5 -5], shape=(2,), dtype=int32)


In [27]:
dataset_shuffle = dataset.shuffle(buffer_size = dataset.cardinality())

In [29]:
epochs = 3

for e in range(epochs):
    print(f"\nEpoch {e}")
    print_dataset(dataset_shuffle)


Epoch 0
tf.Tensor([ 5 -5], shape=(2,), dtype=int32)
tf.Tensor([ 3 -3], shape=(2,), dtype=int32)
tf.Tensor([ 4 -4], shape=(2,), dtype=int32)
tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor([ 1 -1], shape=(2,), dtype=int32)
tf.Tensor([ 2 -2], shape=(2,), dtype=int32)

Epoch 1
tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor([ 2 -2], shape=(2,), dtype=int32)
tf.Tensor([ 1 -1], shape=(2,), dtype=int32)
tf.Tensor([ 4 -4], shape=(2,), dtype=int32)
tf.Tensor([ 3 -3], shape=(2,), dtype=int32)
tf.Tensor([ 5 -5], shape=(2,), dtype=int32)

Epoch 2
tf.Tensor([ 5 -5], shape=(2,), dtype=int32)
tf.Tensor([ 1 -1], shape=(2,), dtype=int32)
tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor([ 3 -3], shape=(2,), dtype=int32)
tf.Tensor([ 2 -2], shape=(2,), dtype=int32)
tf.Tensor([ 4 -4], shape=(2,), dtype=int32)


In [33]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4])

In [35]:
print_dataset(dataset)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [37]:
def preprocess_double(num):
    return 2 * num

dataset_doubled = dataset.map(preprocess_double)

In [39]:
print_dataset(dataset_doubled)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [41]:
dataset_doubled = dataset.map(lambda x : x*2)
print_dataset(dataset_doubled)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [43]:
import glob
import matplotlib.pyplot as plt

In [55]:
image_root = keras.utils.get_file(
    "flower_photos",
    "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz",
    untar = True,
)

In [56]:
image_files = glob.glob(f"{image_root}/*/*.jpg")

In [57]:
image_files[:10]

[]

In [61]:
filepath_dataset = tf.data.Dataset.from_tensor_slices(image_files).take(5)

In [63]:
print_dataset(filepath_dataset)

In [ ]:
def parse_image(file_path):
    raw = tf.io.read_file(file_path)
    image = tf.io.decode_jpeg(raw)
    return image

image_dataset = filepath_dataset.map(parse_image)

In [ ]:
def show_image(image):
    plt.figure()
    plt.imshow(image)
    plt.axis("off")

In [ ]:
for image in image_dataset:
    show_image(image)

In [67]:
layer = keras.layers.Normalization(axis = None)

adapt_data = tf.constant([1,2,3,4,5])
layer.adapt(adapt_data)

In [69]:
layer(tf.constant([-1,2,3,5]))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-2.828427  , -0.70710677,  0.        ,  1.4142135 ], dtype=float32)>

In [71]:
layer_denorm = keras.layers.Normalization(axis = None, invert = True)
layer_denorm.adapt(adapt_data)

In [75]:
normalized = layer(tf.constant([-1, 3, 6]))
layer_denorm(normalized)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.99999976,  3.        ,  6.        ], dtype=float32)>

In [77]:
layer = keras.layers.CategoryEncoding(num_tokens = 5, output_mode = "one_hot")
layer([3,0,4])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [79]:
layer = keras.layers.CategoryEncoding(num_tokens = 5, output_mode = "multi_hot")
layer([[3, 0], [1, 2], [0, 4]])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.]], dtype=float32)>

In [81]:
category_dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4])
encoding_layer = keras.layers.CategoryEncoding(num_tokens = 5, output_mode = "one_hot")

In [83]:
encoded_dataset = category_dataset.map(encoding_layer)

In [85]:
print_dataset(encoded_dataset)

tf.Tensor([[0. 1. 0. 0. 0.]], shape=(1, 5), dtype=float32)
tf.Tensor([[0. 0. 1. 0. 0.]], shape=(1, 5), dtype=float32)
tf.Tensor([[0. 0. 0. 1. 0.]], shape=(1, 5), dtype=float32)
tf.Tensor([[0. 0. 0. 0. 1.]], shape=(1, 5), dtype=float32)


In [87]:
x_train = tf.random.normal([1000, 10])

normalizer = keras.layers.Normalization()
normalizer.adapt(x_train)

In [89]:
model = keras.Sequential(
    [
        keras.Input(shape = (10, )),
        normalizer,
        keras.layers.Dense(4, activation = "relu"),
        keras.layers.Dense(6, activation = "relu"),
        keras.layers.Dense(2),
    ]
)

In [91]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ normalization_2 (Normalization)      │ (None, 10)                  │              21 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 4)                   │              44 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 6)                   │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 2)                   │              14 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 109 (440.00 B)

 Trainable params: 88 (352.00 B)

 Non-trainable params: 21 (88.00 B)

In [93]:
model(tf.random.normal([3, 10]))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.00704715, -0.92447984],
       [-0.86443454, -1.3288966 ],
       [ 0.6600261 , -0.32427505]], dtype=float32)>