### Tensor 생성 함수

In [1]:
import tensorflow as tf

In [3]:
tensor = tf.constant([1, 2])
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [7]:
print(f"data type: {tensor.dtype}")
print(f"number of dimensions: {tensor.ndim}")
print(f"shape: {tensor.shape}")

data type: <dtype: 'int32'>
number of dimensions: 1
shape: (2,)


In [11]:
tensor = tf.constant([1, 1.5])
tensor.dtype

tf.float32

In [13]:
tensor = tf.constant([1, 1.5], dtype = tf.float16)
tensor.dtype

tf.float16

In [15]:
import numpy as np

tensor = tf.constant(
    np.array([[1,2], [3,4]])
)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [17]:
variable_tensor = tf.Variable([1, 2])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [19]:
variable_tensor = tf.Variable(
    np.array([[1, 2],[3, 4]])
)
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [21]:
variable_tensor.assign(
    [[4, 5], [6, 7]]
)
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[4, 5],
       [6, 7]])>

In [23]:
tf.random.normal([1, 3])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.16737351,  1.5531421 ,  0.5483768 ]], dtype=float32)>

In [25]:
tf.random.normal([1, 3], mean=3, stddev=2)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 3.1634507,  5.91868  , -1.5401516]], dtype=float32)>

In [27]:
tf.random.uniform([1, 3])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.61577404, 0.6404271 , 0.17537594]], dtype=float32)>

In [29]:
tf.random.uniform([1, 3], minval=-3, maxval=3)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-2.6867123, -1.9112799, -2.1114721]], dtype=float32)>

In [31]:
tf.ones([1, 3])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>

In [33]:
tf.zeros([1, 3])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>

In [35]:
tf.fill([2, 3], 10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10]])>

### 텐서의 변환과 연산

In [39]:
import numpy as np
import tensorflow as tf

In [41]:
tensor = tf.constant([[1, 2],
                     [3, 4]])

In [43]:
np_array = tensor.numpy()
np_array

array([[1, 2],
       [3, 4]])

In [45]:
type(np_array)

numpy.ndarray

In [47]:
np_array = np.array(tensor)
np_array

array([[1, 2],
       [3, 4]])

In [51]:
a = tf.constant([[1, 2],
               [3, 4]])
b = tf.constant([[1, 1],
                [2, 2]])

In [53]:
add_result = a + b
add_result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

In [55]:
add_result = tf.add(a, b)
add_result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

In [57]:
mul_result = a * b
mul_result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [6, 8]])>

In [59]:
mul_result = tf.multiply(a, b)
mul_result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [6, 8]])>

In [65]:
a = tf.constant([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]])
b = tf.constant([[1, 0, 0],
                [0, 0, 1]])

print(f"a의 열 개수: {a.shape[1]}")
print(f"b의 행 개수: {b.shape[0]}")

a의 열 개수: 2
b의 행 개수: 2


In [67]:
matmul_result = tf.matmul(a, b)
matmul_result

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 0, 2],
       [3, 0, 4],
       [5, 0, 6],
       [7, 0, 8]])>

In [69]:
tensor_int = tf.constant([1, 2], dtype = tf.int32)
tensor_float = tf.constant([3, 4], dtype = tf.float32)

In [73]:
tensor_cast = tf.cast(tensor_float, dtype = tf.int32)
tensor_int + tensor_cast

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>

In [75]:
tensor = tf.constant([3, 5, 7, 9, 10])

In [77]:
tensor[2].numpy()

7

In [79]:
tensor[:2].numpy()

array([3, 5])

### 브로드캐스팅

In [82]:
import tensorflow as tf

In [84]:
a = tf.constant(
    [[1, 2, 3],
     [4, 5, 6]]
)
b = tf.constant([1, -1, 2])

print(f"a의 shape: {a.shape}")
print(f"b의 shape: {b.shape}")

a의 shape: (2, 3)
b의 shape: (3,)


In [86]:
a + b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 1, 5],
       [5, 4, 8]])>

In [88]:
a = tf.constant(
    [[-1, -1],
    [1, 1]]
)

In [90]:
a + 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [2, 2]])>

In [92]:
a * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2, -2],
       [ 2,  2]])>

In [94]:
a = tf.constant(
    [[1, 2, 3],
     [4, 5, 6]]
)
b = tf.constant([1, -1, 2])

print(f"a의 shape: {a.shape}")
print(f"b의 shape: {b.shape}")

a의 shape: (2, 3)
b의 shape: (3,)


In [96]:
b_expanded = tf.constant([[1, -1, 2]])
print(b_expanded.shape)

(1, 3)


In [98]:
a = tf.constant(
    [[1, 2, 3],
     [4, 5, 6]]
)
b = tf.constant([1, -1])

print(f"a의 shape: {a.shape}")
print(f"b의 shape: {b.shape}")

a의 shape: (2, 3)
b의 shape: (2,)


In [100]:
a + b #브로드캐스팅 불가

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [2,3] vs. [2] [Op:AddV2] name: 

### GPU 활용하기

In [104]:
tensor = tf.ones([1, 2])
print(tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0


In [106]:
print(tf.config.list_physical_devices("GPU"))

[]


In [108]:
with tf.device("CPU:0"):
    cpu_tensor = tf.ones([1, 2])

In [110]:
print(cpu_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0


In [112]:
with tf.device("GPU:0"):
    gpu_tensor = tf.ones([1, 2])

In [114]:
print(gpu_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0


### 데이터셋 알아보기

In [117]:
import numpy as np
import tensorflow as tf

In [119]:
x = np.array([0, 1, 2, 3, 4])

In [121]:
dataset = tf.data.Dataset.from_tensor_slices(x)

In [123]:
for data in dataset:
    print(data)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [125]:
x = [[10, 20],
     [20, 15],
     [15, 15],
     [80, 90],
     [85, 80],
     [85, 90]]

In [127]:
dataset = tf.data.Dataset.from_tensor_slices(x)

In [129]:
for data in dataset:
    print(data)

tf.Tensor([10 20], shape=(2,), dtype=int32)
tf.Tensor([20 15], shape=(2,), dtype=int32)
tf.Tensor([15 15], shape=(2,), dtype=int32)
tf.Tensor([80 90], shape=(2,), dtype=int32)
tf.Tensor([85 80], shape=(2,), dtype=int32)
tf.Tensor([85 90], shape=(2,), dtype=int32)


In [131]:
x = [[10, 20],
     [20, 15],
     [15, 15],
     [80, 90],
     [85, 80],
     [85, 90]]

y = [0, 0, 0, 1, 1, 1]

In [133]:
dataset = tf.data.Dataset.from_tensor_slices((x, y))

In [135]:
for data in dataset:
    print(data)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20])>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 15])>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([15, 15])>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([80, 90])>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([85, 80])>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([85, 90])>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)


In [137]:
for data in dataset:
    print(f"x: {data[0]}, y: {data[1]}")

x: [10 20], y: 0
x: [20 15], y: 0
x: [15 15], y: 0
x: [80 90], y: 1
x: [85 80], y: 1
x: [85 90], y: 1


In [139]:
import keras

In [143]:
train_data, test_data = keras.datasets.california_housing.load_data()

x_train, y_train = train_data
x_test, y_test = test_data

In [145]:
x_train[0]

array([-118.27  ,   34.09  ,   52.    , 2327.    ,  555.    , 1048.    ,
        491.    ,    3.7847], dtype=float32)

In [147]:
y_train[0]

252300.0

In [149]:
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))

In [153]:
for train_data in train_dataset:
    print(train_data)
    break

(<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([-118.27  ,   34.09  ,   52.    , 2327.    ,  555.    , 1048.    ,
        491.    ,    3.7847], dtype=float32)>, <tf.Tensor: shape=(), dtype=float32, numpy=252300.0>)
